openapi: 3.1.0
info:
  title: Podorozhnyky API
  version: 1.0.0
  description: API documentation for the "Podorozhnyky" travel blog project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://node-js-project-team-1.onrender.com
  - url: http://localhost:3000
  - url: http://localhost:5000
tags:
  - name: Auth
    description: User authentication and registration
  - name: Users
    description: User profiles and traveler information
  - name: Stories
    description: Travel stories (articles)
  - name: Categories
    description: Story categories

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /stories:
    post:
      $ref: '../swagger/paths/stories/post.yaml'
    get:
      $ref: '../swagger/paths/stories/get.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'
  /auth/send-change-email:
    post:
      $ref: '../swagger/paths/auth/send-change-email.yaml'
  /auth/confirm-email:
    post:
      $ref: '../swagger/paths/auth/confirm-email-change.yaml'
  /auth/get-oauth-url:
    get:
      $ref: '../swagger/paths/auth/get-oauth-url.yaml'
  /auth/login/google:
    post:
      $ref: '../swagger/paths/auth/confirm-oauth.yaml'

  /users:
    get:
      $ref: '../swagger/paths/users/getUsers.yaml'

  /users/me:
    get:
      $ref: '../swagger/paths/users/getUserWithFavorites.yaml'
    patch:
      $ref: '../swagger/paths/users/updateUser.yaml'
  /users/me/stories:
    get:
      $ref: '../swagger/paths/users/get-own-stories.yaml'

  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{userId}/get.yaml

  /users/me/favorites:
    post:
      $ref: '../swagger/paths/users/post-favorite.yaml'

  /users/me/favorites/{storyId}:
    delete:
      $ref: '../swagger/paths/users/me/favourites/delete.yaml'

  /categories:
    get:
      $ref: '../swagger/paths/categories/get-categories.yaml'

  /stories/{id}:
    get:
      $ref: '../swagger/paths/stories/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/stories/{id}/patch.yaml'
components:
  securitySchemes:
    cookieAccess:
      type: apiKey
      in: cookie
      name: accessToken
    cookieRefresh:
      type: apiKey
      in: cookie
      name: refreshToken
    cookieSession:
      type: apiKey
      in: cookie
      name: sessionId
