openapi: 3.1.0
info:
  title: Podorozhnyky API
  version: 1.0.0
  description: API documentation for the "Podorozhnyky" travel blog project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
  - url: http://localhost:5000
tags:
  - name: Auth
    description: User authentication and registration
  - name: Users
    description: User profiles and traveler information
  - name: Stories
    description: Travel stories (articles)
  - name: Categories
    description: Story categories

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/auth/send-reset-email.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/auth/reset-pwd.yaml'

  /users/me/current:
    get:
      $ref: '../swagger/paths/users/getUserWithFavorites.yaml'
  /users/me/current/stories:
    get:
      $ref: '../swagger/paths/users/get-own-stories.yaml'
  /users/me:
    patch:
      $ref: '../swagger/paths/users/updateUser.yaml'

  #   $ref: './paths/users/get-users.yaml'
  # /users/me:
  #   $ref: './paths/users/get-me.yaml'
  # /users/me/patch:
  #   $ref: './paths/users/patch-me.yaml'
  # /users/{userId}:
  #   $ref: './paths/users/get-user-by-id.yaml'

  /users/me/favorites:
    post:
      $ref: '../swagger/paths/users/post-favorite.yaml'
  # /users/me/favorites/{storyId}:
  #   $ref: './paths/users/delete-favorite.yaml'
  # /users/me/favorites:
  #   $ref: './paths/users/post-favorite.yaml'
  /users/me/favorites/{storyId}:
    delete:
      $ref: '../swagger/paths/users/me/favourites/delete.yaml'

  # /stories:
  #   $ref: './paths/stories/get-stories.yaml'
  # /stories/post:
  #   $ref: './paths/stories/post-story.yaml'
  # /stories/{storyId}:
  #   $ref: './paths/stories/patch-story.yaml'

  # /categories:
  #   $ref: './paths/categories/get-categories.yaml'

components:
  securitySchemes:
    cookieAccess:
      type: apiKey
      in: cookie
      name: accessToken
    cookieRefresh:
      type: apiKey
      in: cookie
      name: refreshToken
    cookieSession:
      type: apiKey
      in: cookie
      name: sessionId
