openapi: 3.1.0
info:
  title: Podorozhnyky API
  version: 1.0.0
  description: API documentation for the "Podorozhnyky" travel blog project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3000
tags:
  - name: Auth
    description: User authentication and registration
  - name: Users
    description: User profiles and traveler information
  - name: Stories
    description: Travel stories (articles)
  - name: Categories
    description: Story categories

paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh.yaml'
  /stories:
    post:
      $ref: '../swagger/paths/stories/post.yaml'

components:
  securitySchemes:
    cookieAccess:
      type: apiKey
      in: cookie
      name: accessToken
    cookieRefresh:
      type: apiKey
      in: cookie
      name: refreshToken
    cookieSession:
      type: apiKey
      in: cookie
      name: sessionId
